name: amconfig
version: 0.0.1
description: A sample command-line application.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: '>=0.11.0'
  http: any
  di: ">=3.3.4 <4.0.0"
  yaml: ">=2.1.7 <3.0.0"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
 - di

